// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/subscriber/subscriber.proto

package subscriberv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Subscription) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type AddSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionRequest) Reset() {
	*x = AddSubscriptionRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionRequest) ProtoMessage() {}

func (x *AddSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*AddSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{3}
}

func (x *AddSubscriptionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AddSubscriptionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type AddSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionResponse) Reset() {
	*x = AddSubscriptionResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionResponse) ProtoMessage() {}

func (x *AddSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*AddSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{4}
}

func (x *AddSubscriptionResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AddSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionRequest) Reset() {
	*x = RemoveSubscriptionRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionRequest) ProtoMessage() {}

func (x *RemoveSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSubscriptionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RemoveSubscriptionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type RemoveSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionResponse) Reset() {
	*x = RemoveSubscriptionResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionResponse) ProtoMessage() {}

func (x *RemoveSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveSubscriptionResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{7}
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscriber_subscriber_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscriber_subscriber_proto_rawDescGZIP(), []int{8}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_proto_subscriber_subscriber_proto protoreflect.FileDescriptor

const file_proto_subscriber_subscriber_proto_rawDesc = "" +
	"\n" +
	"!proto/subscriber/subscriber.proto\x12\rsubscriber.v1\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"8\n" +
	"\fSubscription\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"B\n" +
	"\x16AddSubscriptionRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"K\n" +
	"\x17AddSubscriptionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x19RemoveSubscriptionRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"4\n" +
	"\x1aRemoveSubscriptionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\x1a\n" +
	"\x18ListSubscriptionsRequest\"^\n" +
	"\x19ListSubscriptionsResponse\x12A\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1b.subscriber.v1.SubscriptionR\rsubscriptions2\x82\x03\n" +
	"\n" +
	"Subscriber\x12?\n" +
	"\x04Ping\x12\x1a.subscriber.v1.PingRequest\x1a\x1b.subscriber.v1.PingResponse\x12`\n" +
	"\x0fAddSubscription\x12%.subscriber.v1.AddSubscriptionRequest\x1a&.subscriber.v1.AddSubscriptionResponse\x12i\n" +
	"\x12RemoveSubscription\x12(.subscriber.v1.RemoveSubscriptionRequest\x1a).subscriber.v1.RemoveSubscriptionResponse\x12f\n" +
	"\x11ListSubscriptions\x12'.subscriber.v1.ListSubscriptionsRequest\x1a(.subscriber.v1.ListSubscriptionsResponseB:Z8yadro.com/course/proto/gen/go/subscriber/v1;subscriberv1b\x06proto3"

var (
	file_proto_subscriber_subscriber_proto_rawDescOnce sync.Once
	file_proto_subscriber_subscriber_proto_rawDescData []byte
)

func file_proto_subscriber_subscriber_proto_rawDescGZIP() []byte {
	file_proto_subscriber_subscriber_proto_rawDescOnce.Do(func() {
		file_proto_subscriber_subscriber_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscriber_subscriber_proto_rawDesc), len(file_proto_subscriber_subscriber_proto_rawDesc)))
	})
	return file_proto_subscriber_subscriber_proto_rawDescData
}

var file_proto_subscriber_subscriber_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_subscriber_subscriber_proto_goTypes = []any{
	(*PingRequest)(nil),                // 0: subscriber.v1.PingRequest
	(*PingResponse)(nil),               // 1: subscriber.v1.PingResponse
	(*Subscription)(nil),               // 2: subscriber.v1.Subscription
	(*AddSubscriptionRequest)(nil),     // 3: subscriber.v1.AddSubscriptionRequest
	(*AddSubscriptionResponse)(nil),    // 4: subscriber.v1.AddSubscriptionResponse
	(*RemoveSubscriptionRequest)(nil),  // 5: subscriber.v1.RemoveSubscriptionRequest
	(*RemoveSubscriptionResponse)(nil), // 6: subscriber.v1.RemoveSubscriptionResponse
	(*ListSubscriptionsRequest)(nil),   // 7: subscriber.v1.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),  // 8: subscriber.v1.ListSubscriptionsResponse
}
var file_proto_subscriber_subscriber_proto_depIdxs = []int32{
	2, // 0: subscriber.v1.ListSubscriptionsResponse.subscriptions:type_name -> subscriber.v1.Subscription
	0, // 1: subscriber.v1.Subscriber.Ping:input_type -> subscriber.v1.PingRequest
	3, // 2: subscriber.v1.Subscriber.AddSubscription:input_type -> subscriber.v1.AddSubscriptionRequest
	5, // 3: subscriber.v1.Subscriber.RemoveSubscription:input_type -> subscriber.v1.RemoveSubscriptionRequest
	7, // 4: subscriber.v1.Subscriber.ListSubscriptions:input_type -> subscriber.v1.ListSubscriptionsRequest
	1, // 5: subscriber.v1.Subscriber.Ping:output_type -> subscriber.v1.PingResponse
	4, // 6: subscriber.v1.Subscriber.AddSubscription:output_type -> subscriber.v1.AddSubscriptionResponse
	6, // 7: subscriber.v1.Subscriber.RemoveSubscription:output_type -> subscriber.v1.RemoveSubscriptionResponse
	8, // 8: subscriber.v1.Subscriber.ListSubscriptions:output_type -> subscriber.v1.ListSubscriptionsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_subscriber_subscriber_proto_init() }
func file_proto_subscriber_subscriber_proto_init() {
	if File_proto_subscriber_subscriber_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscriber_subscriber_proto_rawDesc), len(file_proto_subscriber_subscriber_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscriber_subscriber_proto_goTypes,
		DependencyIndexes: file_proto_subscriber_subscriber_proto_depIdxs,
		MessageInfos:      file_proto_subscriber_subscriber_proto_msgTypes,
	}.Build()
	File_proto_subscriber_subscriber_proto = out.File
	file_proto_subscriber_subscriber_proto_goTypes = nil
	file_proto_subscriber_subscriber_proto_depIdxs = nil
}
