services:
  api:
    image: api:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.api
    container_name: api
    restart: unless-stopped
    ports:
      - "28080:8080"
    volumes:
      - ./repo-stat/api/config/config.yaml:/config.yaml
    environment:
      - SUBSCRIBER_ADDRESS=subscriber:8080
      - PROCESSOR_ADDRESS=processor:8082
      - COLLECTOR_ADDRESS=collector:8083
    depends_on:
      - subscriber
      - collector
      - processor

  subscriber:
    image: subscriber:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.subscriber
    container_name: subscriber
    restart: unless-stopped
    ports:
      - "28081:8080"
    volumes:
      - ./repo-stat/subscriber/config/config.yaml:/config.yaml
    environment:
      - DB_DSN=postgres://user:password@postgres:5432/subscriptions_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  processor:
    image: processor:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.processor
    container_name: processor
    restart: unless-stopped
    ports:
      - "28082:8082"
    volumes:
      - ./repo-stat/processor/config/config.yaml:/config.yaml
    environment:
      - COLLECTOR_ADDRESS=collector:8083
    depends_on:
      - collector

  collector:
    image: collector:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.collector
    container_name: collector
    restart: unless-stopped
    ports:
      - "28083:8083"
    volumes:
      - ./repo-stat/collector/config/config.yaml:/config.yaml
    environment:
      - SUBSCRIBER_ADDRESS=subscriber:8080
    depends_on:
      - subscriber

  tests:
    image: tests:latest
    build:
      context: tests
    container_name: tests
    restart: "no"
    depends_on:
      - api
    entrypoint: ["true"]

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscriptions_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d subscriptions_db" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata: