// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID          int32              `json:"id"`
	Owner       string             `json:"owner"`
	Repo        string             `json:"repo"`
	FullName    pgtype.Text        `json:"full_name"`
	Description pgtype.Text        `json:"description"`
	Stars       pgtype.Int4        `json:"stars"`
	Forks       pgtype.Int4        `json:"forks"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
