// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInfoByOwnerAndRepo = `-- name: GetInfoByOwnerAndRepo :one
SELECT id, owner, repo, full_name, description, stars, forks, created_at, updated_at
FROM repositories
WHERE owner = $1 AND repo = $2
`

type GetInfoByOwnerAndRepoParams struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) GetInfoByOwnerAndRepo(ctx context.Context, arg GetInfoByOwnerAndRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getInfoByOwnerAndRepo, arg.Owner, arg.Repo)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.FullName,
		&i.Description,
		&i.Stars,
		&i.Forks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllStats = `-- name: ListAllStats :many
SELECT id, owner, repo, full_name, description, stars, forks, created_at, updated_at
FROM repositories
ORDER BY updated_at DESC
`

func (q *Queries) ListAllStats(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listAllStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.FullName,
			&i.Description,
			&i.Stars,
			&i.Forks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInfo = `-- name: UpsertInfo :exec
INSERT INTO repositories (
    owner, repo, full_name, description, stars, forks, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
    )
ON CONFLICT (owner, repo)
DO UPDATE SET
    full_name = EXCLUDED.full_name,
    description = EXCLUDED.description,
    stars = EXCLUDED.stars,
    forks = EXCLUDED.forks,
    updated_at = NOW()
`

type UpsertInfoParams struct {
	Owner       string             `json:"owner"`
	Repo        string             `json:"repo"`
	FullName    pgtype.Text        `json:"full_name"`
	Description pgtype.Text        `json:"description"`
	Stars       pgtype.Int4        `json:"stars"`
	Forks       pgtype.Int4        `json:"forks"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertInfo(ctx context.Context, arg UpsertInfoParams) error {
	_, err := q.db.Exec(ctx, upsertInfo,
		arg.Owner,
		arg.Repo,
		arg.FullName,
		arg.Description,
		arg.Stars,
		arg.Forks,
		arg.CreatedAt,
	)
	return err
}
