// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: collector/collector.proto

package collectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_collector_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_collector_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_collector_collector_proto protoreflect.FileDescriptor

const file_collector_collector_proto_rawDesc = "" +
	"\n" +
	"\x19collector/collector.proto\x12\fcollector.v1\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2J\n" +
	"\tCollector\x12=\n" +
	"\x04Ping\x12\x19.collector.v1.PingRequest\x1a\x1a.collector.v1.PingResponseB'Z%repo-stat/proto/collector;collectorv1b\x06proto3"

var (
	file_collector_collector_proto_rawDescOnce sync.Once
	file_collector_collector_proto_rawDescData []byte
)

func file_collector_collector_proto_rawDescGZIP() []byte {
	file_collector_collector_proto_rawDescOnce.Do(func() {
		file_collector_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_collector_proto_rawDesc), len(file_collector_collector_proto_rawDesc)))
	})
	return file_collector_collector_proto_rawDescData
}

var file_collector_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_collector_collector_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: collector.v1.PingRequest
	(*PingResponse)(nil), // 1: collector.v1.PingResponse
}
var file_collector_collector_proto_depIdxs = []int32{
	0, // 0: collector.v1.Collector.Ping:input_type -> collector.v1.PingRequest
	1, // 1: collector.v1.Collector.Ping:output_type -> collector.v1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collector_collector_proto_init() }
func file_collector_collector_proto_init() {
	if File_collector_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_collector_proto_rawDesc), len(file_collector_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_collector_proto_goTypes,
		DependencyIndexes: file_collector_collector_proto_depIdxs,
		MessageInfos:      file_collector_collector_proto_msgTypes,
	}.Build()
	File_collector_collector_proto = out.File
	file_collector_collector_proto_goTypes = nil
	file_collector_collector_proto_depIdxs = nil
}
