// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID        int32              `json:"id"`
	Owner     string             `json:"owner"`
	Repo      string             `json:"repo"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
