// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package storage

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (owner, repo)
VALUES ($1, $2)
RETURNING id, owner, repo, created_at
`

type CreateSubscriptionParams struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.Owner, arg.Repo)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE owner = $1 AND repo = $2
`

type DeleteSubscriptionParams struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.Owner, arg.Repo)
	return err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT owner, repo
FROM subscriptions
ORDER BY id DESC
`

type ListSubscriptionsRow struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

func (q *Queries) ListSubscriptions(ctx context.Context) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsRow{}
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(&i.Owner, &i.Repo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
