FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o collector ./cmd/collector

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/collector .
EXPOSE 50051
CMD ["./collector"]