FROM golang:1.26-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o gateway ./gateway/cmd

FROM alpine:latest
WORKDIR /root/

COPY --from=builder /app/gateway .
COPY --from=builder /app/docs ./docs

EXPOSE 8080
CMD ["./gateway"]