// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: processor/processor.proto

package processorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_processor_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_processor_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type RepoInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoInfoRequest) Reset() {
	*x = RepoInfoRequest{}
	mi := &file_processor_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoInfoRequest) ProtoMessage() {}

func (x *RepoInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoInfoRequest.ProtoReflect.Descriptor instead.
func (*RepoInfoRequest) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{2}
}

func (x *RepoInfoRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RepoInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stars         int32                  `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
	Forks         int32                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoInfoResponse) Reset() {
	*x = RepoInfoResponse{}
	mi := &file_processor_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoInfoResponse) ProtoMessage() {}

func (x *RepoInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoInfoResponse.ProtoReflect.Descriptor instead.
func (*RepoInfoResponse) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{3}
}

func (x *RepoInfoResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RepoInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RepoInfoResponse) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *RepoInfoResponse) GetForks() int32 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *RepoInfoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SubscribedStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribedStatsRequest) Reset() {
	*x = SubscribedStatsRequest{}
	mi := &file_processor_processor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribedStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribedStatsRequest) ProtoMessage() {}

func (x *SubscribedStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribedStatsRequest.ProtoReflect.Descriptor instead.
func (*SubscribedStatsRequest) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{4}
}

type SubscribedStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*RepoInfoResponse    `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribedStatsResponse) Reset() {
	*x = SubscribedStatsResponse{}
	mi := &file_processor_processor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribedStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribedStatsResponse) ProtoMessage() {}

func (x *SubscribedStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_processor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribedStatsResponse.ProtoReflect.Descriptor instead.
func (*SubscribedStatsResponse) Descriptor() ([]byte, []int) {
	return file_processor_processor_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribedStatsResponse) GetStats() []*RepoInfoResponse {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_processor_processor_proto protoreflect.FileDescriptor

const file_processor_processor_proto_rawDesc = "" +
	"\n" +
	"\x19processor/processor.proto\x12\fprocessor.v1\"\r\n" +
	"\vPingRequest\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"#\n" +
	"\x0fRepoInfoRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x9c\x01\n" +
	"\x10RepoInfoResponse\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05stars\x18\x03 \x01(\x05R\x05stars\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x05R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x18\n" +
	"\x16SubscribedStatsRequest\"O\n" +
	"\x17SubscribedStatsResponse\x124\n" +
	"\x05stats\x18\x01 \x03(\v2\x1e.processor.v1.RepoInfoResponseR\x05stats2\xfb\x01\n" +
	"\tProcessor\x12=\n" +
	"\x04Ping\x12\x19.processor.v1.PingRequest\x1a\x1a.processor.v1.PingResponse\x12L\n" +
	"\vGetRepoInfo\x12\x1d.processor.v1.RepoInfoRequest\x1a\x1e.processor.v1.RepoInfoResponse\x12a\n" +
	"\x12GetSubscribedStats\x12$.processor.v1.SubscribedStatsRequest\x1a%.processor.v1.SubscribedStatsResponseB'Z%repo-stat/proto/processor;processorv1b\x06proto3"

var (
	file_processor_processor_proto_rawDescOnce sync.Once
	file_processor_processor_proto_rawDescData []byte
)

func file_processor_processor_proto_rawDescGZIP() []byte {
	file_processor_processor_proto_rawDescOnce.Do(func() {
		file_processor_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processor_processor_proto_rawDesc), len(file_processor_processor_proto_rawDesc)))
	})
	return file_processor_processor_proto_rawDescData
}

var file_processor_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_processor_processor_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: processor.v1.PingRequest
	(*PingResponse)(nil),            // 1: processor.v1.PingResponse
	(*RepoInfoRequest)(nil),         // 2: processor.v1.RepoInfoRequest
	(*RepoInfoResponse)(nil),        // 3: processor.v1.RepoInfoResponse
	(*SubscribedStatsRequest)(nil),  // 4: processor.v1.SubscribedStatsRequest
	(*SubscribedStatsResponse)(nil), // 5: processor.v1.SubscribedStatsResponse
}
var file_processor_processor_proto_depIdxs = []int32{
	3, // 0: processor.v1.SubscribedStatsResponse.stats:type_name -> processor.v1.RepoInfoResponse
	0, // 1: processor.v1.Processor.Ping:input_type -> processor.v1.PingRequest
	2, // 2: processor.v1.Processor.GetRepoInfo:input_type -> processor.v1.RepoInfoRequest
	4, // 3: processor.v1.Processor.GetSubscribedStats:input_type -> processor.v1.SubscribedStatsRequest
	1, // 4: processor.v1.Processor.Ping:output_type -> processor.v1.PingResponse
	3, // 5: processor.v1.Processor.GetRepoInfo:output_type -> processor.v1.RepoInfoResponse
	5, // 6: processor.v1.Processor.GetSubscribedStats:output_type -> processor.v1.SubscribedStatsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_processor_processor_proto_init() }
func file_processor_processor_proto_init() {
	if File_processor_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processor_processor_proto_rawDesc), len(file_processor_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processor_processor_proto_goTypes,
		DependencyIndexes: file_processor_processor_proto_depIdxs,
		MessageInfos:      file_processor_processor_proto_msgTypes,
	}.Build()
	File_processor_processor_proto = out.File
	file_processor_processor_proto_goTypes = nil
	file_processor_processor_proto_depIdxs = nil
}
